[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1RwhWgQGJu8JNy4DmHgorB9dk47a33uZNI1RDobQoMgo/edit?gid=0#gid=0"
type = "service_account"
project_id = "price-tracker-pipeline-495504"
private_key_id = "787288431b0d76b6f0ccf12032002bb6a3070253"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDT4eKiGybgVtUC
uAZCqu3/frfywxNRjREGfO50xiDcVX2iYhNvxNbKGLTPNfvN1FaOYiBtrUHQOs9x
3ZEOPSvA7CbUndHCRnfdDVXEYnIUpCTiPA24xV1K29B08DKgd2D8bqQYXdwyGIM0
wWFVTHq/al+4oJQU2h121TetoC9OTNUY6ZcunTolQy90UB4u9cVSxAO2K9aDIcrb
jR6lpEpcAgdtu5T9nLDQGB28WDQrhqnBnIMnbxe7wgeTHLxUdtsNb23EihIJmg1D
RT1M+/g52fPLPsA4wQ0Z9msTadWIF3J/+LbD8yfYQx2DatwNvYWveBDlqOyOgLF5
5TMBooOPAgMBAAECggEAD18TVIRYwSy7fluAZMTGyGLWkH+TfraXthtJJ2KaTrHL
EAVCeLjUhkvdjizR7EBL2T+IL7zCigtCMnYLCHfqnS/kr0cVyRzYpEpL3xfvQ80W
uez2Z+G1n3EsAdfNLHQMrrOOJxBkIaRCnIis+YW3X/ylHh1UMOEUAyN7yxZUaD8r
6Wy2obF6fkDA0nsLbAlG3dqGXOrBsML7CkUgiKjjtzJfWytA+2BD/OdUs0pLuW3M
MUmovy5M+nQNtfaaXLH6jJyXH8EmwwatycqmrXFRx1VYAYQi6ku41fYKiusEWSen
Cya9moaB7TI8iVqj8FdeUYADhxbI6iGbv4BNYW/uQQKBgQDqbILc+LWToWOuLU86
b5tF3N3sLdEQ77Y/0GpSaip673m7UL79X5Mj8oHj2q/wEmGtjQDtX1TcHf9UgRbt
oT5FE3/l3w7dEhbO64dij3fFSWByRqdkDj4g1L12LZHlDaDowIxYo3YTXU0jwtlQ
b+YjO2lftOyYlz/VeSAB+iUETwKBgQDnYkBxA9npBs7IT8Kf5mgLeWCnz142RRF5
J2UXCGHbQ9JiKPYD49v6lwjMyZ3EBNE5h2aFLfIAxz7TznV2OAIcGJ57vHABq8/D
9SFOM//rgeZi+Br1MY68CyG5DX8HbvelB7hauG36u2crZCnF0pd2pt40UjyOf5yC
BjSuaxx8wQKBgHPxo2/jWvtfkUuugUcnuCZ/rQuJRaQYy40Yad3FQKl5FD4/G5d5
0+6tnOyzVt1oWgNagCDnS7Nq6sRC7LIvU/saP+HTxyg0MC+7ckSfLN/ZAOjEZTop
iTT3w5VVyJj/epxjz4ZvopDFTsfnMVCFZ8/5LI73jyWReTL+K4SO0gwlAoGABzoj
ZyRGpyemR81t986bi1g0M6mfeLR5kj4vwyNo4w9gP96lqINyeIZFKRhXDCtWWaSo
CBriRzHx/W2ib5naPwRp1tWQ7gxuxeEfNDEdmj6JcqfrN6NfoPH8EKqiQBowNABk
urit/rnhxBIx19L3FiaqJBo5d/32Zn1JIfWIg0ECgYEAlrNTAc7Gn2p+wa8ltIHU
d4cq0WXEvc5b++9XPZt2k2IyexCmidsWH+LWeviP7h4V/7CkE8s6QpRaQuzS6pNr
iUuGnwoT26uaxVq7rCglMARcWaPowCOVPB/OORKYsGzqiYtN5RdsrXh1UrPgrsfU
pvI+nBXfQTct2P8hZ/HU1N8=
-----END PRIVATE KEY-----"""
client_email = "price-tracker-bot@price-tracker-pipeline-495504.iam.gserviceaccount.com"
client_id = "113343865814842394210"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/price-tracker-bot%40price-tracker-pipeline-495504.iam.gserviceaccount.com"